### PR TITLE
Drawing route feature

### PR DESCRIPTION
**Pull request by 1AhmadElmasri**

### CODE REVIEW

**Review by Sn0wCh1ld — CHANGES_REQUESTED** [review]
Could we do the route shape request on the same API call as everything else? That data should be available there, and would make for a cleaner setup (in addition to reducing the number of calls). Additionally, I see some console logs that do not need to be in production. If you would comment them out that would be great

Also, you've uploaded the keys again. We'll need to regenerate them but please avoid this in the future

**Review by skylathadani — CHANGES_REQUESTED** [review]
Looks good to me but we need to hide the keys

**Review by Sn0wCh1ld — CHANGES_REQUESTED** [review]
Line 390: `vehicleMetadata.combFuelConsumption` should be `vehicleMetadata.hwyFuelConsumption` because MapQuest takes highway efficiency as a parameter

Line 388: How come you're sending the string "true" instead of the boolean value?

Also, in your merge conflict fix commit, you re-added the second API call that you had removed one commit earlier

**Review by Sn0wCh1ld — APPROVED** [review]
Looks good to me!

**Review by skylathadani — APPROVED** [review]

**Pull request merged**
